# Generated by Django 2.2.1 on 2022-05-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=4)),
                ('actors', models.TextField(max_length=1028)),
                ('category', models.TextField(max_length=1028)),
                ('synopsis', models.TextField(max_length=11028)),
                ('poster', models.ImageField(default='movie_poster/default.jpg', upload_to='movie_poster')),
            ],
        ),
    ]
