# Generated by Django 2.2.1 on 2022-05-17 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_movies'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='director',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='movies',
            name='runtimes',
            field=models.TextField(default=None, max_length=25),
        ),
        migrations.AddField(
            model_name='movies',
            name='writer',
            field=models.TextField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='movies',
            name='actors',
            field=models.TextField(default=None, max_length=1028),
        ),
        migrations.AlterField(
            model_name='movies',
            name='category',
            field=models.TextField(default=None, max_length=1028),
        ),
        migrations.AlterField(
            model_name='movies',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='movies',
            name='synopsis',
            field=models.TextField(default=None, max_length=11028),
        ),
        migrations.AlterField(
            model_name='movies',
            name='year',
            field=models.CharField(default=None, max_length=4),
        ),
    ]
