# Generated by Django 2.2.1 on 2022-05-19 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_dislike_favorite_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='dislike',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movies',
            name='like',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movies',
            name='watch',
            field=models.BooleanField(default=False),
        ),
    ]
