# Generated by Django 2.2.1 on 2022-05-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_auto_20220519_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='back',
            field=models.URLField(blank=True, default='N/A', null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='wikilink',
            field=models.URLField(blank=True, default='N/A', null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='poster',
            field=models.ImageField(blank=True, default='movie_poster/default.jpg', null=True, upload_to='movie_poster'),
        ),
    ]
