# Generated by Django 2.2.1 on 2022-05-23 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_auto_20220523_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='back',
            new_name='backposter',
        ),
    ]
