# Generated by Django 2.2.1 on 2022-05-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0008_movies_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='rating',
            field=models.CharField(default=0, max_length=15),
        ),
    ]
