# Generated by Django 2.2.1 on 2022-05-27 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0010_recommend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommend',
            name='name',
        ),
    ]
