# Generated by Django 2.2.1 on 2022-05-29 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0011_remove_recommend_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommend',
            name='mid',
            field=models.IntegerField(default=None, unique=True),
        ),
    ]
