# Generated by Django 2.2.1 on 2022-05-29 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0012_auto_20220529_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='region',
            field=models.TextField(default='not set', max_length=255),
        ),
    ]
