# Generated by Django 2.2.1 on 2022-05-29 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0013_movies_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='region',
            new_name='studio',
        ),
    ]
