# Generated by Django 2.2.1 on 2022-05-29 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0015_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='lastmovie',
        ),
    ]
